### ISSUE TITLE
must supply destination port and address in call to Client#statistics

### ISSUE THREAD

**Issue by chemax** [drachtio/rtpengine-client#17]
Hi! Thank you for your lib.
I try to use it and have problem on launch.
```
node app.js 
node:assert:400
    throw err;
    ^

AssertionError [ERR_ASSERTION]: must supply destination port and address in call to Client#statistics
    at Client.<computed> [as statistics] (/root/rtpengineclient/node_modules/rtpengine-client/lib/Client.js:57:12)
    at Client.<anonymous> (/root/rtpengineclient/app.js:5:12)
    at Client.emit (node:events:390:28)
    at Client._onListening (/root/rtpengineclient/node_modules/rtpengine-client/lib/BaseClient.js:105:10)
    at Socket.emit (node:events:390:28)
    at startListening (node:dgram:173:10)
    at node:dgram:365:7
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 0,
  expected: true,
  operator: '=='
}

Node.js v17.2.0
```

my code:
```javascript
const Client = require('rtpengine-client').Client;
const client = new Client('ws://ip:9091');

client.on('listening', () => {
    client.statistics()
      .then((res) => {
        console.log('received data', res);
      })
      .catch((err) => {
        console.log(`Error: ${err}`);
      });
  });
```

What it can be? How i can fix it?

**Comment by chemax** [comment]
I m not so smart how i think
